# example values
spring:
  jpa:
    generate-ddl: true
    properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect
       ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
