# example values
spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
