version: '3'
services:
  postgres:
    image: postgres:16
    container_name: search-engine-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=search_engine